### ISSUE TITLE
Modify MessegerService to receive Chat ID on creation

### ISSUE THREAD

**Issue by yairl** [yairl/r1xbot#57]
Possibly also context.
That way, can use messenger.send(message) and avoid passing chat_id to the messenger, and make get_messenger_and_chat_id simpler -> just make_messenger().

**Comment by nnrepos** [comment]
hey, i want to work on this. i have a few questions though:
* can i assume that `chat_id` remains constant, and therefore can be stored during `MessagingService.__init__`?
* is it ok if i only refactor `chat_id` for this issue? it seems like modifying `ctx` requires lots of refactoring, i could do that in a separate PR/issue.
* are you planning on running tests automatically, e.g. by using git actions? there's not much documentation for the tests, and i was only able to create a telegram bot for now.

thanks
